<?php

/**
 * @file
 * Support for Flickr posts as media entities in Lightning.
 */

use Drupal\lightning_core\OverrideHelper as Override;
use Drupal\lightning_media_flickr\Plugin\MediaEntity\Type\Flickr;

/**
 * Implements hook_media_entity_type_info_alter().
 */
function lightning_media_flickr_media_entity_type_info_alter(array &$types) {
  $types['flickr']['input_match'] = [
    'constraint' => 'FlickrEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $types['flickr']['preview'] = TRUE;

  Override::pluginClass($types['flickr'], Flickr::class);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_media_flickr_form_media_flickr_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('lightning_media.preview.embed_code')->alterForm($form, $form_state);
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lightning_media_flickr_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] == 'media' && $entity_form['#bundle'] == 'flickr') {
    \Drupal::service('lightning_media.preview.embed_code')->alterForm($entity_form, $form_state, $entity_form['#entity']);
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function lightning_media_flickr_entity_extra_field_info() {
  return \Drupal::service('lightning_media.preview.embed_code')->extraFields('flickr');
}
